#GNUMakefile
#Quinton Graham
#used for testing the chess game functions

#compiler used
CC = g++

#include directory
INCLUDE = -I./include

#source files
SRCS = $(wildcard *.cpp) $(wildcard src/*.cpp)

#output file
OUT = chess.exe

#full flags
FLAGS = $(INCLUDE)

all: 
	$(CC) $(SRCS) $(FLAGS) -o $(OUT)